PASER_Crypto_Root Class Reference
PASER_Crypto_Root Class Reference
Cryptography
Class provides functions to generate secrets, compute and check authentication trees.
#include <PASER_Crypto_Root.h>
Public Member Functions
int root_init (int n)
Initialize the object.
int root_regenerate ()
Generate secrets and compute authentication tree.
u_int8_t * root_get_root ()
Get root element.
std::list< u_int8_t * > root_get_next_secret (int *nr, u_int8_t *secret)
Get next secret.
int root_get_iv ()
Get IV.
int root_check_root (u_int8_t *root, u_int8_t *secret, std::list< u_int8_t * > iv_list, u_int32_t iv, u_int32_t *newIV)
Check authentication path of a given secret.
Detailed Description
Class provides functions to generate secrets, compute and check authentication trees.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 34 of file PASER_Crypto_Root.h.
Member Function Documentation
int PASER_Crypto_Root::root_check_root (u_int8_t * root, u_int8_t * secret, std::list< u_int8_t * > iv_list, u_int32_t iv, u_int32_t * newIV)
Check authentication path of a given secret.
Parameters:
root Pointer to the root element corresponding to the authentication path
secret Pointer to the secret corresponding to the authentication path
iv_list Authentication path
iv Last IV of the node
newIV New IV of the node
Returns:
1 if successful or 0 on error
Definition at line 272 of file PASER_Crypto_Root.cc.
References PASER_SECRET_LEN.
int PASER_Crypto_Root::root_get_iv ()
Get IV.
Returns:
IV
Definition at line 189 of file PASER_Crypto_Root.cc.
Referenced by PASER_Message_Processing::forward_ub_rreq(), and PASER_Message_Processing::send_ub_rreq().
std::list< u_int8_t * > PASER_Crypto_Root::root_get_next_secret (int * nr, u_int8_t * secret)
Get next secret.
Parameters:
nr Pointer to next IV
secret Pointer to next secret
Returns:
Authentication path of current secret
Definition at line 133 of file PASER_Crypto_Root.cc.
References PASER_SECRET_LEN.
u_int8_t * PASER_Crypto_Root::root_get_root ()
Get root element.
Returns:
Root element
Definition at line 126 of file PASER_Crypto_Root.cc.
Referenced by PASER_Message_Processing::forward_ub_rreq(), and PASER_Message_Processing::send_ub_rreq().
int PASER_Crypto_Root::root_init (int n)
Initialize the object.
Parameters:
n Number of generated secrets 2^param
Definition at line 54 of file PASER_Crypto_Root.cc.
int PASER_Crypto_Root::root_regenerate ()
Generate secrets and compute authentication tree.
Returns:
1 if successful or 0 on error
Definition at line 64 of file PASER_Crypto_Root.cc.
References PASER_SECRET_LEN.
The documentation for this class was generated from the following files:
src/paser_logic/cryptography/PASER_Crypto_Root.h
src/paser_logic/cryptography/PASER_Crypto_Root.cc