PASER_UU_RREP Class Reference
PASER_UU_RREP Class Reference
Message Structure
Class is an implementation of PASER_UU_RREP messages.
#include <PASER_UU_RREP.h>
Public Member Functions
PASER_UU_RREP (const PASER_UU_RREP &m)
Constructor of PASER_UU_RREP messages. It duplicates an existing message.
PASER_UU_RREP (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_UU_RREP message. It creates a new message.
~PASER_UU_RREP ()
PASER_UU_RREP & operator= (const PASER_UU_RREP &m)
Import the content of another message.
virtual PASER_UU_RREP * dup () const
Duplicates a PASER message.
std::string detailedInfo () const
Produces a multi-line description of the message's content.
u_int8_t * toByteArray (int *l)
Creates and return an array of all fields that must be secured via hash or signature.
u_int8_t * getCompleteByteArray (int *l)
Creates and return an array of all message fields.
Public Attributes
u_int32_t keyNr
Current number of GTK.
u_int8_t GFlag
Gateway flag.
std::list< address_list > AddressRangeList
Route list from querying node to forwarding node.
u_int8_t metricBetweenQueryingAndForw
Metric of the route between querying node and forwarding node.
u_int8_t metricBetweenDestAndForw
Metric of the route between destination node and forwarding node.
lv_block certForw
Certificate of forwarding node.
u_int8_t * root
Root element of forwarding node.
u_int32_t initVector
IV of forwarding node.
geo_pos geoDestination
Geographical position of destination node.
geo_pos geoForwarding
Geographical position of forwarding node.
kdc_block kdc_data
KDC data block.
lv_block sign
Signature of the message.
long timestamp
Sending or forwarding time.
Detailed Description
Class is an implementation of PASER_UU_RREP messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 31 of file PASER_UU_RREP.h.
Constructor & Destructor Documentation
PASER_UU_RREP::PASER_UU_RREP (const PASER_UU_RREP & m)
Constructor of PASER_UU_RREP messages. It duplicates an existing message.
Parameters:
m Pointer to the message to duplicate
Definition at line 27 of file PASER_UU_RREP.cc.
References operator=().
Referenced by dup().
PASER_UU_RREP::PASER_UU_RREP (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_UU_RREP message. It creates a new message.
Parameters:
src IP address of originator
dest IP address of querying node
seqNr Sequence number of originator
Definition at line 32 of file PASER_UU_RREP.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_UU_RREP::~PASER_UU_RREP ()
Destructor
Definition at line 48 of file PASER_UU_RREP.cc.
References certForw, GFlag, kdc_data, root, and sign.
Member Function Documentation
std::string PASER_UU_RREP::detailedInfo () const [virtual]
Produces a multi-line description of the message's content.
Returns:
Description of the message content
Implements PASER_MSG.
Definition at line 151 of file PASER_UU_RREP.cc.
References AddressRangeList, PASER_MSG::destAddress_var, GFlag, keyNr, metricBetweenQueryingAndForw, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
u_int8_t * PASER_UU_RREP::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all message fields.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 382 of file PASER_UU_RREP.cc.
References AddressRangeList, certForw, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, initVector, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, root, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and timestamp.
PASER_UU_RREP & PASER_UU_RREP::operator= (const PASER_UU_RREP & m)
Import the content of another message.
Parameters:
m Pointer to the message the content of which should be imported
Returns:
Reference to myself
Definition at line 63 of file PASER_UU_RREP.cc.
References AddressRangeList, certForw, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, initVector, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, root, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Referenced by PASER_UU_RREP().
u_int8_t * PASER_UU_RREP::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured via hash or signature.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 190 of file PASER_UU_RREP.cc.
References AddressRangeList, certForw, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, initVector, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, root, PASER_MSG::seq, PASER_MSG::srcAddress_var, and timestamp.
Referenced by PASER_Crypto_Sign::checkSignUURREP(), and PASER_Crypto_Sign::signUURREP().
The documentation for this class was generated from the following files:
src/paser_message_structure/PASER_UU_RREP.h
src/paser_message_structure/PASER_UU_RREP.cc