PASER_Routing_Table Class Reference
PASER_Routing_Table Class Reference
Tables
Class is an implementation of the routing table. It provides a map of all existing routes. Each valid route is automatically added to the kernel routing table.
#include <PASER_Routing_Table.h>
Public Member Functions
PASER_Routing_Entry * findAdd (struct in_addr addr)
Find a routing entry for a given destination address (mesh node, client, subnetwork etc.)
PASER_Routing_Entry * findDest (struct in_addr dest_addr)
Find a routing entry for a given mesh node.
std::list< PASER_Routing_Entry * > getListWithNextHop (struct in_addr nextHop)
Get a list of all routes having a given IP address as next hop.
PASER_Routing_Entry * insert (struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_Timer_Message *deltimer, PASER_Timer_Message *validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t *Cert)
Insert a new entry into the map.
PASER_Routing_Entry * update (PASER_Routing_Entry *entry, struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_Timer_Message *deltimer, PASER_Timer_Message *validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t *Cert)
Update an entry in the map.
void delete_entry (PASER_Routing_Entry *entry)
Delete a entry from the map.
PASER_Routing_Entry * getRouteToGw ()
Get the shortest route to the gateway.
PASER_Routing_Entry * findBestGW ()
Get the shortest route to gateway (similar to getRouteToGw()).
void updateKernelRoutingTable (struct in_addr dest_addr, struct in_addr forw_addr, struct in_addr netmask, u_int32_t metric, bool del_entry, int ifIndex)
Add a route to the kernel routing table.
void updateRoutingTableAndSetTableTimeout (std::list< address_range > addList, struct in_addr src_addr, int seq, X509 *cert, struct in_addr nextHop, u_int8_t metric, int ifIndex, struct timeval now, u_int8_t gFlag, bool trusted)
Insert or update an entry in the routing table. If the entry does not exist, a new entry will be added to the table. The delete- and validTimer of the entry will be reseted.
void updateRoutingTableTimeout (struct in_addr src_addr, struct timeval now, int ifIndex)
Reset the delete- and validTimer of an entry. If the entry does not exist, do nothing.
void updateRoutingTableTimeout (struct in_addr src_addr, u_int32_t seq, struct timeval now)
Reset the sequence number, the delete- and validTimer of an entry. If the entry does not exist, do nothing.
void updateRoutingTable (struct timeval now, std::list< address_list > addList, struct in_addr nextHop, int ifIndex)
Insert or update the route of a given list of nodes.
void deleteFromKernelRoutingTableNodesWithNextHopAddr (struct in_addr nextHop)
Delete all entries from routing, neighbor and kernel routing tables and theirs timers the next hop of which is the given IP address.
void updateRouteLifetimes (struct in_addr dest_addr)
Update valid- and deleteTimer of the route entry towards a given destination IP address.
void updateNeighborFromHELLO (address_list liste, u_int32_t seq, int ifIndex)
Update or add a neighbor entry for a list of IP addresses. update or add a routing entry for a list of subnetworks. All entries will be added with a metric equal to 2.
void updateRouteFromHELLO (address_list liste, int ifIndex, struct in_addr nextHop)
Update or add a routing entry for a list of IP addresses. All entries will be added with a metric equal to 3.
std::list< address_list > getNeighborAddressList (int ifNr)
Get all neighbor nodes on a given interface.
Public Attributes
std::map< Uint128,
PASER_Routing_Entry * > route_table
Detailed Description
Class is an implementation of the routing table. It provides a map of all existing routes. Each valid route is automatically added to the kernel routing table.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 43 of file PASER_Routing_Table.h.
Member Function Documentation
void PASER_Routing_Table::delete_entry (PASER_Routing_Entry * entry)
Delete a entry from the map.
Parameters:
Pointer to the entry which will be deleted.
Definition at line 172 of file PASER_Routing_Table.cc.
References PASER_Routing_Entry::dest_addr, and route_table.
Referenced by PASER_Crypto_Sign::checkAllCertInRoutingTable().
void PASER_Routing_Table::deleteFromKernelRoutingTableNodesWithNextHopAddr (struct in_addr nextHop)
Delete all entries from routing, neighbor and kernel routing tables and theirs timers the next hop of which is the given IP address.
Parameters:
nextHop IP address
Definition at line 585 of file PASER_Routing_Table.cc.
References PASER_Routing_Entry::AddL, PASER_Routing_Entry::dest_addr, findDest(), PASER_Neighbor_Table::findNeigh(), getListWithNextHop(), PASER_Routing_Entry::hopcnt, PASER_Routing_Entry::isValid, PASER_Neighbor_Entry::isValid, PASER_Routing_Entry::nxthop_addr, PASER_Timer_Queue::timer_remove(), updateKernelRoutingTable(), PASER_Neighbor_Entry::validTimer, and PASER_Routing_Entry::validTimer.
Referenced by PASER_Route_Maintenance::messageFailed().
PASER_Routing_Entry * PASER_Routing_Table::findBestGW ()
Get the shortest route to gateway (similar to getRouteToGw()).
Returns:
Route to the gateway or NULL if no such route exists.
Definition at line 194 of file PASER_Routing_Table.cc.
References PASER_Routing_Entry::hopcnt, and route_table.
Referenced by findDest(), and getRouteToGw().
PASER_Routing_Entry * PASER_Routing_Table::getRouteToGw ()
Get the shortest route to the gateway.
Returns:
Route to the gateway or NULL if no such route exists.
Definition at line 189 of file PASER_Routing_Table.cc.
References findBestGW().
Referenced by PASER_Crypto_Sign::checkAllCertInRoutingTable(), PASER_Message_Processing::handleUBRREQ(), and updateKernelRoutingTable().
PASER_Routing_Entry * PASER_Routing_Table::update (PASER_Routing_Entry * entry, struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_Timer_Message * deltimer, PASER_Timer_Message * validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t * Cert)
Update an entry in the map.
Parameters:
Pointer to the entry which will be updated.
Definition at line 121 of file PASER_Routing_Table.cc.
References PASER_Routing_Entry::AddL, PASER_Routing_Entry::Cert, PASER_Routing_Entry::deleteTimer, PASER_Routing_Entry::dest_addr, PASER_Routing_Entry::hopcnt, PASER_Routing_Entry::is_gw, PASER_Routing_Entry::isValid, PASER_Routing_Entry::nxthop_addr, route_table, PASER_Routing_Entry::seqnum, and PASER_Routing_Entry::validTimer.
Referenced by updateNeighborFromHELLO(), updateRouteFromHELLO(), updateRoutingTable(), and updateRoutingTableAndSetTableTimeout().
void PASER_Routing_Table::updateKernelRoutingTable (struct in_addr dest_addr, struct in_addr forw_addr, struct in_addr netmask, u_int32_t metric, bool del_entry, int ifIndex)
Add a route to the kernel routing table.
Parameters:
dest_addr IP address of the destination node
forw_addr IP address of the next hop
netmask Network mask of the destination node
metric Metric of the route towards the destination node
del_entry If true, the route will be deleted from the kernel table. Else a new route will be added to the kernel table.
ifIndex Interface over which the destination node is reachable.
Definition at line 225 of file PASER_Routing_Table.cc.
References PASER_Routing_Entry::dest_addr, PASER_Neighbor_Table::findNeigh(), getRouteToGw(), PASER_Neighbor_Entry::neighbor_addr, and PASER_Routing_Entry::nxthop_addr.
Referenced by deleteFromKernelRoutingTableNodesWithNextHopAddr(), PASER_Message_Processing::handleUBRREQ(), updateNeighborFromHELLO(), updateRouteFromHELLO(), updateRoutingTable(), updateRoutingTableAndSetTableTimeout(), and updateRoutingTableTimeout().
void PASER_Routing_Table::updateRoutingTable (struct timeval now, std::list< address_list > addList, struct in_addr nextHop, int ifIndex)
Insert or update the route of a given list of nodes.
Parameters:
addList A list of nodes the route to which will be updated
Definition at line 497 of file PASER_Routing_Table.cc.
References PASER_Timer_Message::data, PASER_Routing_Entry::deleteTimer, PASER_Timer_Message::destAddr, findDest(), PASER_Neighbor_Table::findNeigh(), PASER_Timer_Message::handler, PASER_Routing_Entry::hopcnt, insert(), PASER_Routing_Entry::is_gw, PASER_Neighbor_Entry::neighFlag, PASER_ROUTE_DELETE_TIME, PASER_Routing_Entry::seqnum, PASER_Timer_Message::timeout, PASER_Timer_Queue::timer_add(), update(), updateKernelRoutingTable(), and PASER_Routing_Entry::validTimer.
Referenced by PASER_Message_Processing::handleUBRREQ().
void PASER_Routing_Table::updateRoutingTableAndSetTableTimeout (std::list< address_range > addList, struct in_addr src_addr, int seq, X509 * cert, struct in_addr nextHop, u_int8_t metric, int ifIndex, struct timeval now, u_int8_t gFlag, bool trusted)
Insert or update an entry in the routing table. If the entry does not exist, a new entry will be added to the table. The delete- and validTimer of the entry will be reseted.
Parameters:
src_addr IP address of the node the entry of which will be updated.
Definition at line 272 of file PASER_Routing_Table.cc.
References PASER_Routing_Entry::Cert, PASER_Timer_Message::data, PASER_Routing_Entry::deleteTimer, PASER_Routing_Entry::dest_addr, PASER_Timer_Message::destAddr, findDest(), PASER_Neighbor_Table::findNeigh(), PASER_Timer_Message::handler, PASER_Routing_Entry::hopcnt, PASER_Neighbor_Entry::ifIndex, insert(), PASER_Routing_Entry::is_gw, PASER_Routing_Entry::isValid, PASER_Neighbor_Entry::isValid, PASER_Neighbor_Entry::neighFlag, PASER_Routing_Entry::nxthop_addr, PASER_ROUTE_DELETE_TIME, PASER_Routing_Entry::seqnum, PASER_Timer_Message::timeout, PASER_Timer_Queue::timer_add(), update(), updateKernelRoutingTable(), and PASER_Routing_Entry::validTimer.
Referenced by PASER_Message_Processing::handleUBRREQ().
Member Data Documentation
std::map<Uint128, PASER_Routing_Entry*> PASER_Routing_Table::route_table
Map of all node's routes. Key - IP address of the node. Value - Pointer to the corresponding route entry.
Definition at line 50 of file PASER_Routing_Table.h.
Referenced by delete_entry(), findAdd(), findBestGW(), findDest(), getListWithNextHop(), getNeighborAddressList(), insert(), PASER_Global::resetPASER(), and update().
The documentation for this class was generated from the following files:
src/paser_tables/PASER_Routing_Table.h
src/paser_tables/PASER_Routing_Table.cc