PASER_UB_RREQ Class Reference
PASER_UB_RREQ Class Reference
Message Structure
Class is an implementation of PASER_UB_RREQ messages.
#include <PASER_UB_RREQ.h>
Public Member Functions
PASER_UB_RREQ (const PASER_UB_RREQ &m)
Constructor of PASER_UU_RREQ messages. It duplicates an existing message.
PASER_UB_RREQ (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_UU_RREQ message. It creates a new message.
PASER_UB_RREQ & operator= (const PASER_UB_RREQ &m)
Import the content of another message.
virtual PASER_UB_RREQ * dup () const
Duplicates a PASER message.
std::string detailedInfo () const
Produces a multi-line description of the message's content.
u_int8_t * toByteArray (int *l)
Creates and return an array of all fields that must be secured via hash or signature.
u_int8_t * getCompleteByteArray (int *l)
Creates and return an array of all message fields.
Public Attributes
u_int32_t keyNr
Current number of GTK.
u_int32_t seqForw
Sequence number of forwarding node.
u_int8_t GFlag
Gateway flag.
std::list< address_list > AddressRangeList
Route list from querying node to forwarding node.
u_int8_t metricBetweenQueryingAndForw
Metric of the route between querying node and forwarding node.
lv_block cert
Certificate of sending node.
u_int32_t nonce
Registration nonce of sending node.
lv_block certForw
Certificate of forwarding node.
u_int8_t * root
RooT element of forwarding node.
u_int32_t initVector
IV of forwarding node.
geo_pos geoQuerying
Geographical position of sending node.
geo_pos geoForwarding
Geographical position of forwarding node.
lv_block sign
Signature of the message.
long timestamp
Sending or forwarding time.
Detailed Description
Class is an implementation of PASER_UB_RREQ messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 34 of file PASER_UB_RREQ.h.
Constructor & Destructor Documentation
PASER_UB_RREQ::PASER_UB_RREQ (const PASER_UB_RREQ & m)
Constructor of PASER_UU_RREQ messages. It duplicates an existing message.
Parameters:
m Pointer to the message to duplicate
Definition at line 28 of file PASER_UB_RREQ.cc.
References operator=().
Referenced by dup().
PASER_UB_RREQ::PASER_UB_RREQ (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_UU_RREQ message. It creates a new message.
Parameters:
src IP address of sending node
dest IP address of querying node
seqNr Sequence number of sending node
Definition at line 34 of file PASER_UB_RREQ.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Member Function Documentation
std::string PASER_UB_RREQ::detailedInfo () const [virtual]
Produces a multi-line description of the message's content.
Returns:
Description of the message content
Implements PASER_MSG.
Definition at line 128 of file PASER_UB_RREQ.cc.
References AddressRangeList, PASER_MSG::destAddress_var, geoForwarding, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
u_int8_t * PASER_UB_RREQ::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all message fields.
Parameters:
l Length of the created array
Returns:
Array
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
message array
Implements PASER_MSG.
Definition at line 309 of file PASER_UB_RREQ.cc.
References AddressRangeList, cert, certForw, PASER_MSG::destAddress_var, geoForwarding, geoQuerying, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, nonce, root, PASER_MSG::seq, seqForw, sign, PASER_MSG::srcAddress_var, and timestamp.
PASER_UB_RREQ & PASER_UB_RREQ::operator= (const PASER_UB_RREQ & m)
Import the content of another message.
Parameters:
m Pointer to the message the content of which should be imported
Returns:
Reference to myself
Definition at line 63 of file PASER_UB_RREQ.cc.
References AddressRangeList, cert, certForw, PASER_MSG::destAddress_var, geoForwarding, geoQuerying, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, nonce, root, PASER_MSG::seq, seqForw, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Referenced by PASER_UB_RREQ().
u_int8_t * PASER_UB_RREQ::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured via hash or signature.
Parameters:
l Length of the created array
Returns:
Array
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
message array
Implements PASER_MSG.
Definition at line 159 of file PASER_UB_RREQ.cc.
References AddressRangeList, cert, certForw, PASER_MSG::destAddress_var, geoForwarding, geoQuerying, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, nonce, root, PASER_MSG::seq, seqForw, PASER_MSG::srcAddress_var, and timestamp.
Referenced by PASER_Crypto_Sign::checkSignUBRREQ(), and PASER_Crypto_Sign::signUBRREQ().
The documentation for this class was generated from the following files:
src/paser_message_structure/PASER_UB_RREQ.h
src/paser_message_structure/PASER_UB_RREQ.cc