PASER_TB_Hello Class Reference
PASER_TB_Hello Class Reference
Message Structure
Class is an implementation of PASER_TB_Hello messages.
#include <PASER_TB_Hello.h>
Public Member Functions
PASER_TB_Hello (const PASER_TB_Hello &m)
Constructor of PASER_TB_Hello messages. It duplicates an existing message.
PASER_TB_Hello (struct in_addr src, u_int32_t seqNr)
Constructor of the PASER_TB_Hello message. It creates a new message.
PASER_TB_Hello & operator= (const PASER_TB_Hello &m)
Import the content of another message.
virtual PASER_TB_Hello * dup () const
Duplicates a PASER message.
std::string detailedInfo () const
Produces a multi-line description of the message's content.
u_int8_t * toByteArray (int *l)
Creates and return an array of all fields that must be secured via hash or signature.
u_int8_t * getCompleteByteArray (int *l)
Creates and return an array of all message fields.
Public Attributes
std::list< address_list > AddressRangeList
Address range list of sending node.
geo_pos geoQuerying
Geographical position of sending node.
u_int8_t * secret
Secret of sending node.
std::list< u_int8_t * > auth
Authentication path of sending node.
u_int8_t * hash
Hash of the message.
Detailed Description
Class is an implementation of PASER_TB_Hello messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 34 of file PASER_TB_Hello.h.
Constructor & Destructor Documentation
PASER_TB_Hello::PASER_TB_Hello (const PASER_TB_Hello & m)
Constructor of PASER_TB_Hello messages. It duplicates an existing message.
Parameters:
m Pointer to the message to duplicate
Definition at line 29 of file PASER_TB_Hello.cc.
References operator=().
Referenced by dup().
PASER_TB_Hello::PASER_TB_Hello (struct in_addr src, u_int32_t seqNr)
Constructor of the PASER_TB_Hello message. It creates a new message.
Parameters:
src IP address of sending node
seqNr Sequence number of sending node
Definition at line 34 of file PASER_TB_Hello.cc.
References PASER_MSG::destAddress_var, hash, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Member Function Documentation
std::string PASER_TB_Hello::detailedInfo () const [virtual]
Produces a multi-line description of the message's content.
Returns:
Description of the message content
Implements PASER_MSG.
Definition at line 100 of file PASER_TB_Hello.cc.
References AddressRangeList, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
u_int8_t * PASER_TB_Hello::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all message fields.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 211 of file PASER_TB_Hello.cc.
References AddressRangeList, auth, geoQuerying, hash, PASER_SECRET_LEN, secret, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
PASER_TB_Hello & PASER_TB_Hello::operator= (const PASER_TB_Hello & m)
Import the content of another message.
Parameters:
m Pointer to the message the content of which should be imported
Returns:
Reference to myself
Definition at line 59 of file PASER_TB_Hello.cc.
References AddressRangeList, auth, PASER_MSG::destAddress_var, geoQuerying, hash, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_TB_Hello().
u_int8_t * PASER_TB_Hello::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured via hash or signature.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 110 of file PASER_TB_Hello.cc.
References AddressRangeList, auth, geoQuerying, PASER_SECRET_LEN, secret, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
Referenced by PASER_Crypto_Hash::checkHmacHELLO(), and PASER_Crypto_Hash::computeHmacHELLO().
The documentation for this class was generated from the following files:
src/paser_message_structure/PASER_TB_Hello.h
src/paser_message_structure/PASER_TB_Hello.cc