PASER_Neighbor_Table Class Reference
PASER_Neighbor_Table Class Reference
Tables
Class is an implementation of the neighbor table. It provides a map of node's neighbors.
#include <PASER_Neighbor_Table.h>
Public Member Functions
PASER_Neighbor_Entry * findNeigh (struct in_addr neigh_addr)
Find a routing entry for a given destination address.
PASER_Neighbor_Entry * insert (struct in_addr neigh_addr, PASER_Timer_Message *deleteTimer, PASER_Timer_Message *validTimer, int neighFlag, u_int8_t *root, u_int32_t IV, geo_pos position, u_int8_t *Cert, u_int32_t ifIndex)
Insert an new entry into the map.
PASER_Neighbor_Entry * update (PASER_Neighbor_Entry *entry, struct in_addr neigh_addr, PASER_Timer_Message *deleteTimer, PASER_Timer_Message *validTimer, int neighFlag, u_int8_t *root, u_int32_t IV, geo_pos position, u_int8_t *Cert, u_int32_t ifIndex)
Update an entry in the map.
void delete_entry (PASER_Neighbor_Entry *entry)
Delete a entry from the map.
void updateNeighborTableAndSetTableTimeout (struct in_addr neigh, int nFlag, u_int8_t *root, int iv, geo_pos position, X509 *cert, struct timeval now, u_int32_t ifIndex)
Insert or update an entry in the neighbor table. If the entry does not exist then a new entry will be added to the table. Hereby, Delete- and ValidTimer of the entry will be reseted.
void updateNeighborTableTimeout (struct in_addr neigh, struct timeval now)
Reset the Delete- and ValidTimer of an entry. If the entry does not exist, do nothing.
void updateNeighborTableIVandSetValid (struct in_addr neigh, u_int32_t IV)
Update IV of an entry and mark the entry as valid If the entry does not exist, do nothing.
void updateNeighborTableIV (struct in_addr neigh, u_int32_t IV)
Update IV of an entry. If the entry does not exist, do nothing.
Public Attributes
std::map< Uint128,
PASER_Neighbor_Entry * > neighbor_table_map
Map of node's neighbors. Key - IP address of the node. Value - Pointer to the corresponding neighbor entry.
Detailed Description
Class is an implementation of the neighbor table. It provides a map of node's neighbors.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 40 of file PASER_Neighbor_Table.h.
Member Function Documentation
void PASER_Neighbor_Table::delete_entry (PASER_Neighbor_Entry * entry)
Delete a entry from the map.
Parameters:
Pointer Pointer to the entry which will be deleted
Definition at line 105 of file PASER_Neighbor_Table.cc.
References PASER_Neighbor_Entry::neighbor_addr, and neighbor_table_map.
Referenced by PASER_Crypto_Sign::checkAllCertInRoutingTable().
PASER_Neighbor_Entry * PASER_Neighbor_Table::update (PASER_Neighbor_Entry * entry, struct in_addr neigh_addr, PASER_Timer_Message * deleteTimer, PASER_Timer_Message * validTimer, int neighFlag, u_int8_t * root, u_int32_t IV, geo_pos position, u_int8_t * Cert, u_int32_t ifIndex)
Update an entry in the map.
Parameters:
Pointer Pointer to the entry which will be updated.
Definition at line 72 of file PASER_Neighbor_Table.cc.
References PASER_Neighbor_Entry::Cert, PASER_Neighbor_Entry::deleteTimer, PASER_Neighbor_Entry::ifIndex, PASER_Neighbor_Entry::isValid, PASER_Neighbor_Entry::IV, PASER_Neighbor_Entry::neighbor_addr, neighbor_table_map, PASER_Neighbor_Entry::neighFlag, PASER_Neighbor_Entry::position, PASER_Neighbor_Entry::root, and PASER_Neighbor_Entry::validTimer.
Referenced by updateNeighborTableAndSetTableTimeout().
void PASER_Neighbor_Table::updateNeighborTableAndSetTableTimeout (struct in_addr neigh, int nFlag, u_int8_t * root, int iv, geo_pos position, X509 * cert, struct timeval now, u_int32_t ifIndex)
Insert or update an entry in the neighbor table. If the entry does not exist then a new entry will be added to the table. Hereby, Delete- and ValidTimer of the entry will be reseted.
Parameters:
IP Address of the neighbor node the entry of which will be updated.
Definition at line 121 of file PASER_Neighbor_Table.cc.
References PASER_Timer_Message::data, PASER_Neighbor_Entry::deleteTimer, PASER_Timer_Message::destAddr, findNeigh(), PASER_Timer_Message::handler, insert(), PASER_Neighbor_Entry::neighFlag, PASER_Timer_Message::timeout, PASER_Timer_Queue::timer_add(), update(), and PASER_Neighbor_Entry::validTimer.
Referenced by PASER_Message_Processing::handleUBRREQ().
The documentation for this class was generated from the following files:
src/paser_tables/PASER_Neighbor_Table.h
src/paser_tables/PASER_Neighbor_Table.cc