PASER_UB_Key_Refresh Class Reference
PASER_UB_Key_Refresh Class Reference
Message Structure
Class is an implementation of PASER_UB_Key_Refresh messages.
#include <PASER_UB_Key_Refresh.h>
Public Member Functions
PASER_UB_Key_Refresh (const PASER_UB_Key_Refresh &m)
Constructor of PASER_UB_Key_Refresh messages. It duplicates an existing message.
PASER_UB_Key_Refresh (struct in_addr src)
Constructor of the PASER_UB_Key_Refresh message. It creates a new message.
~PASER_UB_Key_Refresh ()
PASER_UB_Key_Refresh & operator= (const PASER_UB_Key_Refresh &m)
Import the content of another message.
virtual PASER_UB_Key_Refresh * dup () const
Duplicates a PASER message.
std::string detailedInfo () const
Produces a multi-line description of the message's content.
u_int8_t * toByteArray (int *l)
Creates and return an array of all fields that must be secured via hash or signature.
u_int8_t * getCompleteByteArray (int *l)
Creates and return an array of all message fields.
Public Attributes
u_int32_t keyNr
Current number of GTK.
lv_block cert
Certificate of KDC.
lv_block sign
Signature of the message.
Detailed Description
Class is an implementation of PASER_UB_Key_Refresh messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 35 of file PASER_UB_Key_Refresh.h.
Constructor & Destructor Documentation
PASER_UB_Key_Refresh::PASER_UB_Key_Refresh (const PASER_UB_Key_Refresh & m)
Constructor of PASER_UB_Key_Refresh messages. It duplicates an existing message.
Parameters:
m Pointer to the message to duplicate
Definition at line 28 of file PASER_UB_Key_Refresh.cc.
References operator=().
Referenced by dup().
PASER_UB_Key_Refresh::PASER_UB_Key_Refresh (struct in_addr src)
Constructor of the PASER_UB_Key_Refresh message. It creates a new message.
Parameters:
src IP address of sending node
Definition at line 33 of file PASER_UB_Key_Refresh.cc.
References PASER_MSG::destAddress_var, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_UB_Key_Refresh::~PASER_UB_Key_Refresh ()
Destructor
Definition at line 47 of file PASER_UB_Key_Refresh.cc.
References cert, and sign.
Member Function Documentation
std::string PASER_UB_Key_Refresh::detailedInfo () const [virtual]
Produces a multi-line description of the message's content.
Returns:
Description of the message content
Implements PASER_MSG.
Definition at line 77 of file PASER_UB_Key_Refresh.cc.
References keyNr, and PASER_MSG::srcAddress_var.
u_int8_t * PASER_UB_Key_Refresh::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all message fields.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 120 of file PASER_UB_Key_Refresh.cc.
References cert, keyNr, sign, and PASER_MSG::srcAddress_var.
PASER_UB_Key_Refresh & PASER_UB_Key_Refresh::operator= (const PASER_UB_Key_Refresh & m)
Import the content of another message.
Parameters:
m Pointer to the message the content of which should be imported
Returns:
Reference to myself
Definition at line 52 of file PASER_UB_Key_Refresh.cc.
References cert, PASER_MSG::destAddress_var, keyNr, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_UB_Key_Refresh().
u_int8_t * PASER_UB_Key_Refresh::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured via hash or signature.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 86 of file PASER_UB_Key_Refresh.cc.
References cert, and keyNr.
Referenced by PASER_Crypto_Sign::checkSignRESET().
The documentation for this class was generated from the following files:
src/paser_message_structure/PASER_UB_Key_Refresh.h
src/paser_message_structure/PASER_UB_Key_Refresh.cc