PASER_Message_Processing Class Reference
PASER_Message_Processing Class Reference
Message Processing
Class provides functions to manage all PASER messages.
#include <PASER_Message_Processing.h>
Public Member Functions
void handleLowerMsg (cPacket *msg, u_int32_t ifIndex)
Process a received PASER message. Checks its type and call the corresponding functions to handle the latter.
int check_seq_nr (PASER_MSG *paser_msg, struct in_addr forwarding)
Check sequence number of the PASER message.
int check_geo (geo_pos position)
Check if the specified position is in the range of own wireless card.
int checkRouteList (std::list< address_list > rList)
Check if IP address of own wireless card is in the list.
void handleUBRREQ (cPacket *msg, u_int32_t ifIndex)
Functions to process a received PASER message. Check the message, edit routing and neighbor tables and send a reply or forward the message, if necessary.
PASER_UB_RREQ * send_ub_rreq (struct in_addr src_addr, struct in_addr dest_addr, int isDestGW)
Functions to send a PASER message.
PASER_UB_RREQ * forward_ub_rreq (PASER_UB_RREQ *oldMessage)
void deleteRouteRequestTimeout (struct in_addr dest_addr)
Delete an IP address from rreq_list as well as the corresponding timer from timer_queue.
void deleteRouteRequestTimeoutForAddList (std::list< address_list > AddList)
Delete a list of IP addresses from rreq_list as well as the corresponding timers from timer_queue.
void sendKDCRequest (struct in_addr nodeAddr, struct in_addr nextHop, lv_block cert, int nonce)
Send a registration request to KDC. The request will be sent over Ethernet. This function is only called by a gateway.
void checkKDCReply (cPacket *msg)
Check the KDC registration reply and forward it to the destination node.
Detailed Description
Class provides functions to manage all PASER messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 42 of file PASER_Message_Processing.h.
Member Function Documentation
int PASER_Message_Processing::check_geo (geo_pos position)
Check if the specified position is in the range of own wireless card.
Parameters:
position Geo Position
Returns:
1 if the position is in the range of own wireless card else 0.
Funktion prueft GeoPosition des Absenders
Returns:
: 1 - Absender befindet sich in WLAN Radius 0 - false
Definition at line 304 of file PASER_Message_Processing.cc.
References PASER_radius.
Referenced by handleUBRREQ().
int PASER_Message_Processing::check_seq_nr (PASER_MSG * paser_msg, struct in_addr forwarding)
Check sequence number of the PASER message.
Parameters:
paser_msr Pointer to the message
forwarding IP address of the node which forwarded the message
Returns:
1 if the sequence number is fresh else 0
Funktion prueft den Sequenznummer des Pakets return 1: message is new 0: message is old
Definition at line 155 of file PASER_Message_Processing.cc.
References PASER_MSG::destAddress_var, PASER_Routing_Table::findDest(), PASER_MSG::seq, PASER_UB_RREQ::seqForw, PASER_TU_RREQ::seqForw, PASER_Routing_Entry::seqnum, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by handleUBRREQ().
int PASER_Message_Processing::checkRouteList (std::list< address_list > rList)
Check if IP address of own wireless card is in the list.
Parameters:
rList List of IP addresses
Returns:
1 IP address of own wireless card is in the list else 0.
Definition at line 331 of file PASER_Message_Processing.cc.
Referenced by handleUBRREQ().
void PASER_Message_Processing::deleteRouteRequestTimeout (struct in_addr dest_addr)
Delete an IP address from rreq_list as well as the corresponding timer from timer_queue.
Parameters:
dest_addr IP address to delete
Definition at line 2589 of file PASER_Message_Processing.cc.
References PASER_RREQ_List::pending_find(), PASER_RREQ_List::pending_remove(), and PASER_Timer_Queue::timer_remove().
Referenced by handleUBRREQ().
void PASER_Message_Processing::deleteRouteRequestTimeoutForAddList (std::list< address_list > AddList)
Delete a list of IP addresses from rreq_list as well as the corresponding timers from timer_queue.
Parameters:
AddList List of IP addresses to delete
Definition at line 2601 of file PASER_Message_Processing.cc.
References PASER_RREQ_List::pending_find_addr_with_mask(), PASER_RREQ_List::pending_remove(), and PASER_Timer_Queue::timer_remove().
Referenced by handleUBRREQ().
PASER_UB_RREQ * PASER_Message_Processing::forward_ub_rreq (PASER_UB_RREQ * oldMessage)
Functions to forward a PASER message
Definition at line 2076 of file PASER_Message_Processing.cc.
References PASER_UB_RREQ::AddressRangeList, PASER_UB_RREQ::certForw, PASER_UB_RREQ::geoForwarding, PASER_Crypto_Sign::getCert(), PASER_UB_RREQ::initVector, PASER_UB_RREQ::metricBetweenQueryingAndForw, PASER_UB_RREQ::root, PASER_Crypto_Root::root_get_iv(), PASER_Crypto_Root::root_get_root(), PASER_UB_RREQ::seqForw, PASER_Crypto_Sign::signUBRREQ(), and PASER_UB_RREQ::timestamp.
Referenced by handleUBRREQ().
void PASER_Message_Processing::handleUBRREQ (cPacket * msg, u_int32_t ifIndex)
Functions to process a received PASER message. Check the message, edit routing and neighbor tables and send a reply or forward the message, if necessary.
Process UBRREQ message
Definition at line 344 of file PASER_Message_Processing.cc.
References PASER_UB_RREQ::AddressRangeList, PASER_UB_RREQ::cert, PASER_Routing_Entry::Cert, PASER_UB_RREQ::certForw, check_geo(), check_seq_nr(), PASER_Crypto_Sign::checkOneCert(), checkRouteList(), PASER_Crypto_Sign::checkSignUBRREQ(), PASER_Timer_Message::data, deleteRouteRequestTimeout(), deleteRouteRequestTimeoutForAddList(), PASER_Routing_Entry::dest_addr, PASER_Timer_Message::destAddr, PASER_MSG::destAddress_var, PASER_Crypto_Sign::extractCert(), PASER_Routing_Table::findAdd(), PASER_Routing_Table::findDest(), PASER_Neighbor_Table::findNeigh(), forward_ub_rreq(), PASER_UB_RREQ::geoForwarding, PASER_Routing_Table::getRouteToGw(), PASER_UB_RREQ::GFlag, PASER_Timer_Message::handler, PASER_Routing_Entry::hopcnt, PASER_Neighbor_Entry::ifIndex, PASER_UB_RREQ::initVector, PASER_Configurations::isAddInMySubnetz(), PASER_Crypto_Sign::isGwCert(), PASER_Routing_Entry::isValid, PASER_Neighbor_Entry::isValid, PASER_UB_RREQ::keyNr, PASER_UB_RREQ::metricBetweenQueryingAndForw, PASER_Neighbor_Entry::neighFlag, PASER_UB_RREQ::nonce, PASER_Routing_Entry::nxthop_addr, PASER_UU_RREP_WAIT_TIME, PASER_RREQ_List::pending_add(), PASER_RREQ_List::pending_find(), PASER_UB_RREQ::root, PASER_Message_Queue::send_queued_messages(), PASER_Message_Queue::send_queued_messages_for_AddList(), sendKDCRequest(), PASER_MSG::seq, PASER_UB_RREQ::seqForw, PASER_MSG::srcAddress_var, PASER_Timer_Message::timeout, PASER_Timer_Queue::timer_add(), PASER_Timer_Queue::timer_remove(), PASER_UB_RREQ::timestamp, PASER_Routing_Table::updateKernelRoutingTable(), PASER_Neighbor_Table::updateNeighborTableAndSetTableTimeout(), PASER_Routing_Table::updateRoutingTable(), and PASER_Routing_Table::updateRoutingTableAndSetTableTimeout().
Referenced by handleLowerMsg().
void PASER_Message_Processing::sendKDCRequest (struct in_addr nodeAddr, struct in_addr nextHop, lv_block cert, int nonce)
Send a registration request to KDC. The request will be sent over Ethernet. This function is only called by a gateway.
Parameters:
nodeAddr IP address of the registered node
nextHop IP address of the next hop node to the registered node
cert certificate of the registered node
nonce nonce of the registered node
Definition at line 2623 of file PASER_Message_Processing.cc.
Referenced by handleUBRREQ().
The documentation for this class was generated from the following files:
src/paser_logic/message_processing/PASER_Message_Processing.h
src/paser_logic/message_processing/PASER_Message_Processing.cc