PASER_Route_Discovery Class Reference
PASER_Route_Discovery Class Reference
Route Discovery
Class provides functions to manage a node registration at a gateway or to handle a route discovery.
#include <PASER_Route_Discovery.h>
Public Member Functions
void tryToRegister ()
Start registration of the node at a gateway (only if the node is not registered).
void route_discovery (struct in_addr dest_addr, int isDestGW)
Start route discovery (only if not already started)
void processMessage (IPv4Datagram *datagram)
Process a data message. If the route to the message destination is not known, then start a route discovery.
Detailed Description
Class provides functions to manage a node registration at a gateway or to handle a route discovery.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 31 of file PASER_Route_Discovery.h.
Member Function Documentation
void PASER_Route_Discovery::processMessage (IPv4Datagram * datagram)
Process a data message. If the route to the message destination is not known, then start a route discovery.
Parameters:
datagram Pointer to the data message
Definition at line 94 of file PASER_Route_Discovery.cc.
References PASER_Routing_Table::findDest(), PASER_Neighbor_Table::findNeigh(), PASER_Routing_Entry::hopcnt, PASER_Configurations::isAddInMySubnetz(), PASER_Routing_Entry::isValid, PASER_Neighbor_Entry::isValid, PASER_Message_Queue::message_add(), PASER_Neighbor_Entry::neighFlag, PASER_Routing_Entry::nxthop_addr, route_discovery(), and PASER_RERR_List::setRerrTime().
void PASER_Route_Discovery::route_discovery (struct in_addr dest_addr, int isDestGW)
Start route discovery (only if not already started)
Parameters:
dest_addr IP address of destination node or broadcast if isDestGW is set.
isDestGW Flag is set if a route to a gateway must be found.
Definition at line 47 of file PASER_Route_Discovery.cc.
References PASER_Timer_Message::data, PASER_Timer_Message::destAddr, PASER_Timer_Message::handler, PASER_UB_RREQ_WAIT_TIME, PASER_RREQ_List::pending_add(), PASER_RREQ_List::pending_find(), PASER_Message_Processing::send_ub_rreq(), PASER_Timer_Message::timeout, and PASER_Timer_Queue::timer_add().
Referenced by processMessage(), and tryToRegister().
The documentation for this class was generated from the following files:
src/paser_logic/route_discovery/PASER_Route_Discovery.h
src/paser_logic/route_discovery/PASER_Route_Discovery.cc