PASER_Route_Maintenance Class Reference
PASER_Route_Maintenance Class Reference
Route Maintenance
Class provides functions to keep routes up-to-date. It manages PASER timers and link layer feedback.
#include <PASER_Route_Maintenance.h>
Public Member Functions
void handleSelfMsg (cMessage *msg)
This function is called when a timer expires. It checks the expired timer's type and call the corresponding functions to handle the latter.
void messageFailed (struct in_addr src, struct in_addr dest, bool sendRERR)
Process a link layer feedback. Delete unreachable routes from routing and neighbor tables.
Detailed Description
Class provides functions to keep routes up-to-date. It manages PASER timers and link layer feedback.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 31 of file PASER_Route_Maintenance.h.
Member Function Documentation
void PASER_Route_Maintenance::handleSelfMsg (cMessage * msg)
This function is called when a timer expires. It checks the expired timer's type and call the corresponding functions to handle the latter.
Parameters:
msg Pointer to the expired timer
Definition at line 33 of file PASER_Route_Maintenance.cc.
References PASER_Timer_Message::handler, PASER_Timer_Message::timeout, and PASER_Timer_Queue::timer_get_next_timer().
void PASER_Route_Maintenance::messageFailed (struct in_addr src, struct in_addr dest, bool sendRERR)
Process a link layer feedback. Delete unreachable routes from routing and neighbor tables.
Parameters:
src Not used !!!
dest IP address of the node the route to which has been broken
sendRERR Decision whether to send a RERR message or not
Definition at line 416 of file PASER_Route_Maintenance.cc.
References PASER_Routing_Table::deleteFromKernelRoutingTableNodesWithNextHopAddr(), PASER_Routing_Entry::dest_addr, PASER_Routing_Table::findDest(), PASER_Neighbor_Table::findNeigh(), PASER_Routing_Table::getListWithNextHop(), PASER_Neighbor_Entry::neighbor_addr, PASER_Routing_Entry::nxthop_addr, and PASER_Routing_Entry::seqnum.
The documentation for this class was generated from the following files:
src/paser_logic/route_maintenance/PASER_Route_Maintenance.h
src/paser_logic/route_maintenance/PASER_Route_Maintenance.cc