PASER_Crypto_Hash Class Reference
PASER_Crypto_Hash Class Reference
Cryptography
Class provides functions to compute and check the hash value of PASER messages.
#include <PASER_Crypto_Hash.h>
Public Member Functions
int computeHmacTURREQ (PASER_TU_RREQ *message, lv_block GTK)
Compute a hash value of the PASER_TU_RREQ message using GTK and append this value to the message.
int checkHmacTURREQ (PASER_TU_RREQ *message, lv_block GTK)
Check the hash value of a PASER_TU_RREQ value.
int computeHmacTURREP (PASER_TU_RREP *message, lv_block GTK)
Compute a hash value of a PASER_TU_RREP message using GTK and append this value to the message.
int checkHmacTURREP (PASER_TU_RREP *message, lv_block GTK)
Check a hash value of a PASER_TU_RREP message.
int computeHmacTURREPACK (PASER_TU_RREP_ACK *message, lv_block GTK)
Compute the hash value of a PASER_TU_RREP_ACK message using GTK and append the hash value to the message.
int checkHmacTURREPACK (PASER_TU_RREP_ACK *message, lv_block GTK)
Check the hash value of a PASER_TU_RREP_ACK message.
int computeHmacRERR (PASER_TB_RERR *message, lv_block GTK)
Compute the hash value of a PASER_TB_RERR message using GTK and append the hash value to the message.
int checkHmacRERR (PASER_TB_RERR *message, lv_block GTK)
Check the hash value of a PASER_TB_RERR message.
int computeHmacHELLO (PASER_TB_Hello *message, lv_block GTK)
Compute the hash value of a PASER_TB_Hello message using GTK and append the hash value to the message.
int checkHmacHELLO (PASER_TB_Hello *message, lv_block GTK)
Verify the hash value of a PASER_TB_Hello message.
Detailed Description
Class provides functions to compute and check the hash value of PASER messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 36 of file PASER_Crypto_Hash.h.
Member Function Documentation
int PASER_Crypto_Hash::checkHmacHELLO (PASER_TB_Hello * message, lv_block GTK)
Verify the hash value of a PASER_TB_Hello message.
Parameters:
message Pointer to the PASER_TB_Hello message the hash value of which will be verified
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 286 of file PASER_Crypto_Hash.cc.
References PASER_TB_Hello::hash, and PASER_TB_Hello::toByteArray().
int PASER_Crypto_Hash::checkHmacRERR (PASER_TB_RERR * message, lv_block GTK)
Check the hash value of a PASER_TB_RERR message.
Parameters:
message Pointer to the PASER_TB_RERR message the hash value of which will be verified
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 240 of file PASER_Crypto_Hash.cc.
References PASER_TB_RERR::hash, and PASER_TB_RERR::toByteArray().
int PASER_Crypto_Hash::checkHmacTURREP (PASER_TU_RREP * message, lv_block GTK)
Check a hash value of a PASER_TU_RREP message.
Parameters:
message Pointer to the PASER_TU_RREP message the hash value of which will be verified
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 116 of file PASER_Crypto_Hash.cc.
References PASER_TU_RREP::hash, and PASER_TU_RREP::toByteArray().
int PASER_Crypto_Hash::checkHmacTURREPACK (PASER_TU_RREP_ACK * message, lv_block GTK)
Check the hash value of a PASER_TU_RREP_ACK message.
Parameters:
message Pointer to the PASER_TU_RREP_ACK message the hash value of which will be verified
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 171 of file PASER_Crypto_Hash.cc.
References PASER_TU_RREP_ACK::hash, and PASER_TU_RREP_ACK::toByteArray().
int PASER_Crypto_Hash::checkHmacTURREQ (PASER_TU_RREQ * message, lv_block GTK)
Check the hash value of a PASER_TU_RREQ value.
Parameters:
message Pointer to the PASER_TU_RREQ the hash value of which will be verified
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 63 of file PASER_Crypto_Hash.cc.
References PASER_TU_RREQ::hash, and PASER_TU_RREQ::toByteArray().
int PASER_Crypto_Hash::computeHmacHELLO (PASER_TB_Hello * message, lv_block GTK)
Compute the hash value of a PASER_TB_Hello message using GTK and append the hash value to the message.
Parameters:
message Pointer to the PASER_TB_Hello message the hash value of which will be computed
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 265 of file PASER_Crypto_Hash.cc.
References PASER_TB_Hello::hash, and PASER_TB_Hello::toByteArray().
int PASER_Crypto_Hash::computeHmacRERR (PASER_TB_RERR * message, lv_block GTK)
Compute the hash value of a PASER_TB_RERR message using GTK and append the hash value to the message.
Parameters:
message Pointer to the PASER_TB_RERR message the hash value of which which will be computed
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 219 of file PASER_Crypto_Hash.cc.
References PASER_TB_RERR::hash, and PASER_TB_RERR::toByteArray().
int PASER_Crypto_Hash::computeHmacTURREP (PASER_TU_RREP * message, lv_block GTK)
Compute a hash value of a PASER_TU_RREP message using GTK and append this value to the message.
Parameters:
message Pointer to the PASER_TU_RREP message the hash value will be computed
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 96 of file PASER_Crypto_Hash.cc.
References PASER_TU_RREP::hash, and PASER_TU_RREP::toByteArray().
int PASER_Crypto_Hash::computeHmacTURREPACK (PASER_TU_RREP_ACK * message, lv_block GTK)
Compute the hash value of a PASER_TU_RREP_ACK message using GTK and append the hash value to the message.
Parameters:
message Pointer to the PASER_TU_RREP_ACK message the hash value of which will be computed
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 140 of file PASER_Crypto_Hash.cc.
References PASER_TU_RREP_ACK::hash, and PASER_TU_RREP_ACK::toByteArray().
int PASER_Crypto_Hash::computeHmacTURREQ (PASER_TU_RREQ * message, lv_block GTK)
Compute a hash value of the PASER_TU_RREQ message using GTK and append this value to the message.
Parameters:
message Pointer to the PASER_TU_RREQ message the hash value of which will be computed
GTK Current GTK
Returns:
1 if successful or 0 on error
Definition at line 34 of file PASER_Crypto_Hash.cc.
References PASER_TU_RREQ::hash, and PASER_TU_RREQ::toByteArray().
The documentation for this class was generated from the following files:
src/paser_logic/cryptography/PASER_Crypto_Hash.h
src/paser_logic/cryptography/PASER_Crypto_Hash.cc