PASER_Message_Queue Class Reference
PASER_Message_Queue Class Reference
Buffer
Class is a buffer of all data messages that must be forwarded to an unknown destination.
#include <PASER_Message_Queue.h>
Public Member Functions
PASER_Message_Queue (PASER_Socket *pModul)
Constructor of PASER_Message_Queue.
void message_add (cPacket *p, struct in_addr dest_addr)
Add a new data message to Container.
void getAllPaketsTo (struct in_addr dest_addr, std::list< message_queue_entry > *datagrams)
Get a list of all buffered messages for the destination with the IP address dest_addr delete these messages from container.
void getAllPaketsToAddWithMask (struct in_addr dest_addr, struct in_addr mask_addr, std::list< message_queue_entry > *datagrams)
Get a list of all buffered messages for the destination with the IP address dest_addr and the network mask mask_addr delete these messages from container.
void send_queued_messages (struct in_addr dest_addr)
Send all messages in container to the dest_addr IP address.
void send_queued_messages_for_AddList (std::list< address_list > AddList)
Send all messages in container to the destinations listed in AddList
void deleteMessages (struct in_addr dest_addr)
Delete all messages for destination dest_addr from container.
Public Attributes
std::list< message_queue_entry > message_queue_list
Container for data messages.
Detailed Description
Class is a buffer of all data messages that must be forwarded to an unknown destination.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 42 of file PASER_Message_Queue.h.
Constructor & Destructor Documentation
PASER_Message_Queue::PASER_Message_Queue (PASER_Socket * pModul)
Constructor of PASER_Message_Queue.
Parameters:
pModul Pointer to the PASER module
Definition at line 34 of file PASER_Message_Queue.cc.
Member Function Documentation
void PASER_Message_Queue::deleteMessages (struct in_addr dest_addr)
Delete all messages for destination dest_addr from container.
Parameters:
dest_addr IP address for the messages destination
Definition at line 136 of file PASER_Message_Queue.cc.
References getAllPaketsTo().
void PASER_Message_Queue::getAllPaketsTo (struct in_addr dest_addr, std::list< message_queue_entry > * datagrams)
Get a list of all buffered messages for the destination with the IP address dest_addr delete these messages from container.
Parameters:
dest_addr IP address of the message destination
datagrams List of all buffered messages for that destination
Definition at line 46 of file PASER_Message_Queue.cc.
References message_queue_list.
Referenced by deleteMessages(), and send_queued_messages().
void PASER_Message_Queue::getAllPaketsToAddWithMask (struct in_addr dest_addr, struct in_addr mask_addr, std::list< message_queue_entry > * datagrams)
Get a list of all buffered messages for the destination with the IP address dest_addr and the network mask mask_addr delete these messages from container.
Parameters:
dest_addr IP address of the message destination
mask_addr Network mask of the destination IP address
datagrams List of all buffered messages for that destination
Definition at line 65 of file PASER_Message_Queue.cc.
References message_queue_list.
Referenced by send_queued_messages_for_AddList().
void PASER_Message_Queue::message_add (cPacket * p, struct in_addr dest_addr)
Add a new data message to Container.
Parameters:
p Pointer to the message
dest_addr IP address of the message destination
Definition at line 38 of file PASER_Message_Queue.cc.
References message_queue_list.
Referenced by PASER_Route_Discovery::processMessage().
void PASER_Message_Queue::send_queued_messages (struct in_addr dest_addr)
Send all messages in container to the dest_addr IP address.
Parameters:
dest_addr IP address of the messages destination
Definition at line 85 of file PASER_Message_Queue.cc.
References getAllPaketsTo(), and PASER_DATA_PACKET_SEND_DELAY.
Referenced by PASER_Message_Processing::handleUBRREQ().
void PASER_Message_Queue::send_queued_messages_for_AddList (std::list< address_list > AddList)
Send all messages in container to the destinations listed in AddList
Parameters:
AddList List IP addresses for which the messages should be sent
Definition at line 107 of file PASER_Message_Queue.cc.
References getAllPaketsToAddWithMask(), and PASER_DATA_PACKET_SEND_DELAY.
Referenced by PASER_Message_Processing::handleUBRREQ().
The documentation for this class was generated from the following files:
src/paser_buffer/PASER_Message_Queue.h
src/paser_buffer/PASER_Message_Queue.cc