PASER_Crypto_Sign Class Reference
PASER_Crypto_Sign Class Reference
Cryptography
Class provides functions to compute and check signatures of PASER messages.
#include <PASER_Crypto_Sign.h>
Public Member Functions
void init (char *certPath, char *keyPath, char *CAcertPath)
int getCert (lv_block *cert)
X509 * extractCert (lv_block cert)
int signUBRREQ (PASER_UB_RREQ *message)
int checkSignUBRREQ (PASER_UB_RREQ *message)
int checkSignKDC (kdc_block data)
int signUURREP (PASER_UU_RREP *message)
int checkSignUURREP (PASER_UU_RREP *message)
int signB_ROOT (PASER_UB_Root_Refresh *message)
int checkSignB_ROOT (PASER_UB_Root_Refresh *message)
int checkSignRESET (PASER_UB_Key_Refresh *message)
u_int8_t isGwCert (X509 *cert)
u_int8_t isKdcCert (X509 *cert)
int rsa_encrypt (lv_block in, lv_block *out, X509 *cert)
int rsa_dencrypt (lv_block in, lv_block *out)
int setCRL (lv_block in)
int checkOneCert (X509 *cert)
int checkAllCertInRoutingTable (PASER_Routing_Table *routing_table, PASER_Neighbor_Table *neighbor_table, PASER_Timer_Queue *timer_queue)
Detailed Description
Class provides functions to compute and check signatures of PASER messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 52 of file PASER_Crypto_Sign.h.
Member Function Documentation
int PASER_Crypto_Sign::checkAllCertInRoutingTable (PASER_Routing_Table * routing_table, PASER_Neighbor_Table * neighbor_table, PASER_Timer_Queue * timer_queue)
The function checks whether all certificates in routing and neighbor tables are valid. All routes that correspond to an invalid certificate will be deleted.
Parameters:
routing_table Pointer to the routing table object
neighbor_table Pointer to the neighbor table object
timer_queue Pointer to the timer queue
Returns:
1 if a valid route to a gateway exist. Else 0.
Definition at line 809 of file PASER_Crypto_Sign.cc.
References PASER_Neighbor_Entry::Cert, checkOneCert(), PASER_Neighbor_Table::delete_entry(), PASER_Routing_Table::delete_entry(), PASER_Neighbor_Entry::deleteTimer, PASER_Routing_Entry::deleteTimer, PASER_Routing_Table::getListWithNextHop(), PASER_Routing_Table::getRouteToGw(), PASER_Neighbor_Entry::neighbor_addr, PASER_Neighbor_Table::neighbor_table_map, PASER_Timer_Queue::timer_remove(), PASER_Neighbor_Entry::validTimer, and PASER_Routing_Entry::validTimer.
Referenced by PASER_Message_Processing::checkKDCReply().
int PASER_Crypto_Sign::checkOneCert (X509 * cert)
Check whether a certificate is valid
Parameters:
cert Pointer to the certificate
Returns:
1 if successful or 0 on error
Definition at line 744 of file PASER_Crypto_Sign.cc.
Referenced by checkAllCertInRoutingTable(), checkSignB_ROOT(), checkSignRESET(), checkSignUBRREQ(), checkSignUURREP(), and PASER_Message_Processing::handleUBRREQ().
int PASER_Crypto_Sign::checkSignB_ROOT (PASER_UB_Root_Refresh * message)
Check the signature of a PASER_UB_Root_Refresh message
Parameters:
message Pointer to the PASER_UB_Root_Refresh message
Returns:
1 if successful or 0 on error
Definition at line 369 of file PASER_Crypto_Sign.cc.
References PASER_UB_Root_Refresh::cert, checkOneCert(), PASER_UB_Root_Refresh::sign, and PASER_UB_Root_Refresh::toByteArray().
int PASER_Crypto_Sign::checkSignKDC (kdc_block data)
Check the signature of a KDC_block message
Parameters:
data KDC_block
Returns:
1 if successful or 0 on error
Definition at line 494 of file PASER_Crypto_Sign.cc.
References extractCert().
Referenced by PASER_Message_Processing::checkKDCReply().
int PASER_Crypto_Sign::checkSignRESET (PASER_UB_Key_Refresh * message)
Check the signature of a PASER_UB_Key_Refresh message
Parameters:
message Pointer to the PASER_UB_Key_Refresh message
Returns:
1 if successful or 0 on error
Definition at line 444 of file PASER_Crypto_Sign.cc.
References PASER_UB_Key_Refresh::cert, checkOneCert(), PASER_UB_Key_Refresh::sign, and PASER_UB_Key_Refresh::toByteArray().
int PASER_Crypto_Sign::checkSignUBRREQ (PASER_UB_RREQ * message)
Check the signature of a PASER_UB_RREQ message
Parameters:
message Pointer to the PASER_TU_RREQ message
Returns:
1 if successful or 0 on error
Definition at line 182 of file PASER_Crypto_Sign.cc.
References PASER_UB_RREQ::certForw, checkOneCert(), PASER_UB_RREQ::sign, and PASER_UB_RREQ::toByteArray().
Referenced by PASER_Message_Processing::handleUBRREQ().
int PASER_Crypto_Sign::checkSignUURREP (PASER_UU_RREP * message)
Check the signature of a PASER_UU_RREP message
Parameters:
message Pointer to the PASER_UU_RREP message
Returns:
1 if successful or 0 on error
Definition at line 276 of file PASER_Crypto_Sign.cc.
References PASER_UU_RREP::certForw, checkOneCert(), PASER_UU_RREP::sign, and PASER_UU_RREP::toByteArray().
X509 * PASER_Crypto_Sign::extractCert (lv_block cert)
Extract a X509 certificate from acchar array
Parameters:
cert lv_block which contains both, the certificate and the char array
Returns:
Pointer to certificate if successful or NULL on error
Definition at line 631 of file PASER_Crypto_Sign.cc.
Referenced by checkSignKDC(), and PASER_Message_Processing::handleUBRREQ().
int PASER_Crypto_Sign::getCert (lv_block * cert)
Get own certificate as char array
Parameters:
cert Pointer to the lv_block which will be written
Returns:
1 if successful or 0 on error
Definition at line 115 of file PASER_Crypto_Sign.cc.
Referenced by PASER_Message_Processing::forward_ub_rreq(), and PASER_Message_Processing::send_ub_rreq().
void PASER_Crypto_Sign::init (char * certPath, char * keyPath, char * CAcertPath)
Initialization of PASER_Crypto_Sign Object. The function loads own certificate, asymmetric private key and CA certificate.!!!
Parameters:
certPath Path to the own certificate
keyPath Path to the asymmetric private key
CAcertPath Path to the CA certificate
Definition at line 40 of file PASER_Crypto_Sign.cc.
u_int8_t PASER_Crypto_Sign::isGwCert (X509 * cert)
Check if a certificate belongs to the Gateway
Parameters:
cert Pointer to the certificate
Returns:
1 if successful or 0 on error
Definition at line 650 of file PASER_Crypto_Sign.cc.
Referenced by PASER_Message_Processing::handleUBRREQ().
u_int8_t PASER_Crypto_Sign::isKdcCert (X509 * cert)
Check if a certificate belongs to KDC
Parameters:
cert Pointer to the certificate
Returns:
1 if successful or 0 on error
Definition at line 674 of file PASER_Crypto_Sign.cc.
int PASER_Crypto_Sign::rsa_dencrypt (lv_block in, lv_block * out)
Decrypt a char array with a own asymmetric private key
Parameters:
in Char array to be decrypted
out Pointer to the decrypted char array!!!
Returns:
1 on successful or 0 on error
Definition at line 723 of file PASER_Crypto_Sign.cc.
Referenced by PASER_Message_Processing::checkKDCReply().
int PASER_Crypto_Sign::rsa_encrypt (lv_block in, lv_block * out, X509 * cert)
Encrypt a char array with a public key of given certificate
Parameters:
in Char array to be encrypted
out Pointer to the encrypted char array
cert Pointer to the certificate
Returns:
1 on successful or 0 on error
Definition at line 698 of file PASER_Crypto_Sign.cc.
int PASER_Crypto_Sign::setCRL (lv_block in)
Set CRL from char array!!!
Parameters:
in Char array which contains CRL
Returns:
1 if successful or 0 on error
Definition at line 133 of file PASER_Crypto_Sign.cc.
int PASER_Crypto_Sign::signB_ROOT (PASER_UB_Root_Refresh * message)
Compute the signature of a PASER_UB_Root_Refresh message and append the signature to the message
Parameters:
message Pointer to the PASER_UB_Root_Refresh message
Returns:
1 if successful or 0 on error
Definition at line 340 of file PASER_Crypto_Sign.cc.
References PASER_sign_len, PASER_UB_Root_Refresh::sign, and PASER_UB_Root_Refresh::toByteArray().
int PASER_Crypto_Sign::signUBRREQ (PASER_UB_RREQ * message)
Compute a signature of a PASER_UB_RREQ message and append the signature to the message
Parameters:
message Pointer to the PASER_TU_RREQ message
Returns:
1 if successful or 0 on error
Definition at line 152 of file PASER_Crypto_Sign.cc.
References PASER_sign_len, PASER_UB_RREQ::sign, and PASER_UB_RREQ::toByteArray().
Referenced by PASER_Message_Processing::forward_ub_rreq(), and PASER_Message_Processing::send_ub_rreq().
int PASER_Crypto_Sign::signUURREP (PASER_UU_RREP * message)
Compute the signature of a PASER_UU_RREP message and append the signature to the message
Parameters:
message Pointer to the PASER_UU_RREP message
Returns:
1 if successful or 0 on error
Definition at line 228 of file PASER_Crypto_Sign.cc.
References PASER_sign_len, PASER_UU_RREP::sign, and PASER_UU_RREP::toByteArray().
The documentation for this class was generated from the following files:
src/paser_logic/cryptography/PASER_Crypto_Sign.h
src/paser_logic/cryptography/PASER_Crypto_Sign.cc