PASER_TB_RERR Class Reference
PASER_TB_RERR Class Reference
Message Structure
Class is an implementation of PASER_TB_RERR messages.
#include <PASER_TB_RERR.h>
Public Member Functions
PASER_TB_RERR (const PASER_TB_RERR &m)
Constructor of PASER_TB_RERR messages. It duplicates an existing message.
PASER_TB_RERR (struct in_addr src, u_int32_t seqNr)
Constructor of the PASER_TB_RERR message. It creates a new message.
PASER_TB_RERR & operator= (const PASER_TB_RERR &m)
Import the content of another message.
virtual PASER_TB_RERR * dup () const
Duplicates a PASER message.
std::string detailedInfo () const
Produces a multi-line description of the message's content.
u_int8_t * toByteArray (int *l)
Creates and return an array of all fields that must be secured via hash or signature.
u_int8_t * getCompleteByteArray (int *l)
Creates and return an array of all message fields.
Public Attributes
u_int32_t keyNr
Current number of GTK.
std::list< unreachableBlock > UnreachableAdressesList
List of unreachable addresses.
geo_pos geoForwarding
Geographical position of forwarding node.
u_int8_t * secret
Secret of forwarding node.
std::list< u_int8_t * > auth
Authentication path of forwarding node.
u_int8_t * hash
Hash of the message.
Detailed Description
Class is an implementation of PASER_TB_RERR messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 34 of file PASER_TB_RERR.h.
Constructor & Destructor Documentation
PASER_TB_RERR::PASER_TB_RERR (const PASER_TB_RERR & m)
Constructor of PASER_TB_RERR messages. It duplicates an existing message.
Parameters:
m Pointer to the message to duplicate
Definition at line 29 of file PASER_TB_RERR.cc.
References operator=().
Referenced by dup().
PASER_TB_RERR::PASER_TB_RERR (struct in_addr src, u_int32_t seqNr)
Constructor of the PASER_TB_RERR message. It creates a new message.
Parameters:
src IP address of sending node
seqNr Sequence number of sending node
Definition at line 34 of file PASER_TB_RERR.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Member Function Documentation
std::string PASER_TB_RERR::detailedInfo () const [virtual]
Produces a multi-line description of the message's content.
Returns:
Description of the message content
Implements PASER_MSG.
Definition at line 109 of file PASER_TB_RERR.cc.
References keyNr, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
u_int8_t * PASER_TB_RERR::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all message fields.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 271 of file PASER_TB_RERR.cc.
References auth, geoForwarding, hash, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and UnreachableAdressesList.
PASER_TB_RERR & PASER_TB_RERR::operator= (const PASER_TB_RERR & m)
Import the content of another message.
Parameters:
m Pointer to the message the content of which should be imported
Returns:
Reference to myself
Definition at line 54 of file PASER_TB_RERR.cc.
References auth, PASER_MSG::destAddress_var, geoForwarding, hash, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, PASER_MSG::type, and UnreachableAdressesList.
Referenced by PASER_TB_RERR().
u_int8_t * PASER_TB_RERR::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured via hash or signature.
Parameters:
l Length of the created array
Returns:
Array
Implements PASER_MSG.
Definition at line 128 of file PASER_TB_RERR.cc.
References auth, geoForwarding, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and UnreachableAdressesList.
Referenced by PASER_Crypto_Hash::checkHmacRERR(), and PASER_Crypto_Hash::computeHmacRERR().
The documentation for this class was generated from the following files:
src/paser_message_structure/PASER_TB_RERR.h
src/paser_message_structure/PASER_TB_RERR.cc